CREATE TABLE [dbo].[AuthorMaster] (
    [Id]            UNIQUEIDENTIFIER NOT NULL,
    [Name]          VARCHAR (150)    NULL,
    [Description]   VARCHAR (250)    NULL,
    [Address]       VARCHAR (250)    NULL,
    [CityId]        UNIQUEIDENTIFIER NOT NULL,
    [StateId]       UNIQUEIDENTIFIER NOT NULL,
    [CountryId]     UNIQUEIDENTIFIER NOT NULL,
    [ZipCode]       VARCHAR (50)     NULL,
    [Phone]         VARCHAR (50)     NULL,
    [Mobile]        VARCHAR (50)     NULL,
    [Email]         VARCHAR (100)    NULL,
    [CompanyId]     UNIQUEIDENTIFIER NOT NULL,
    [SchoolId]      UNIQUEIDENTIFIER NOT NULL,
    [IsActive]      BIT              DEFAULT ((1)) NOT NULL,
    [IsDeleted]     BIT              DEFAULT ((0)) NOT NULL,
    [CreatedBy]     UNIQUEIDENTIFIER NULL,
    [CreatedDate]   DATETIME         DEFAULT (getdate()) NOT NULL,
    [ModifiedBy]    UNIQUEIDENTIFIER NULL,
    [ModifiedDate]  DATETIME         NULL,
    [Status]        CHAR (10)        DEFAULT ('INC') NOT NULL,
    [StatusMessage] NVARCHAR (255)   NULL,
    CONSTRAINT [PK_AUTHORMaster] PRIMARY KEY CLUSTERED ([Id] ASC)
);

