CREATE TABLE [dbo].[BookMaster] (
    [Id]              UNIQUEIDENTIFIER NOT NULL,
    [Code]            VARCHAR (50)     NULL,
    [Title]           VARCHAR (150)    NULL,
    [Description]     VARCHAR (250)    NULL,
    [Image]           VARCHAR (100)    NULL,
    [TypeId]          UNIQUEIDENTIFIER NOT NULL,
    [CategoryId]      UNIQUEIDENTIFIER NOT NULL,
    [AuthorId]        UNIQUEIDENTIFIER NOT NULL,
    [PublisherId]     UNIQUEIDENTIFIER NOT NULL,
    [SupplierId]      UNIQUEIDENTIFIER NULL,
    [Edition]         VARCHAR (50)     NULL,
    [NoOfCopies]      INT              NULL,
    [StockInHand]     INT              NULL,
    [PublishingDate]  DATETIME         NULL,
    [ISBNNumber]      VARCHAR (50)     NULL,
    [Price]           DECIMAL (18, 2)  NULL,
    [TotalPages]      INT              NULL,
    [IsIssuable]      BIT              NOT NULL,
    [CallNumber]      VARCHAR (50)     NULL,
    [AccessionNumber] VARCHAR (50)     NULL,
    [IsActive]        BIT              DEFAULT ((1)) NOT NULL,
    [IsDeleted]       BIT              DEFAULT ((0)) NOT NULL,
    [CompanyId]       UNIQUEIDENTIFIER NOT NULL,
    [SchoolId]        UNIQUEIDENTIFIER NOT NULL,
    [CreatedBy]       UNIQUEIDENTIFIER NULL,
    [CreatedDate]     DATETIME         DEFAULT (getdate()) NOT NULL,
    [ModifiedBy]      UNIQUEIDENTIFIER NULL,
    [ModifiedDate]    DATETIME         NULL,
    [Status]          VARCHAR (10)     DEFAULT ('INC') NULL,
    [StatusMessage]   NVARCHAR (255)   NULL,
    CONSTRAINT [PK_BookMaster] PRIMARY KEY CLUSTERED ([Id] ASC)
);

