CREATE TABLE [dbo].[DriverMaster] (
    [Id]                   UNIQUEIDENTIFIER NOT NULL,
    [FirstName]            VARCHAR (50)     NOT NULL,
    [LastName]             VARCHAR (50)     NULL,
    [FathersName]          VARCHAR (100)    NULL,
    [DOB]                  DATETIME         NULL,
    [QualifcationId]       UNIQUEIDENTIFIER NOT NULL,
    [Mobile_Phone]         VARCHAR (50)     NULL,
    [Address]              VARCHAR (50)     NULL,
    [Phone]                VARCHAR (50)     NULL,
    [CityId]               UNIQUEIDENTIFIER NOT NULL,
    [StateId]              UNIQUEIDENTIFIER NOT NULL,
    [CountryId]            UNIQUEIDENTIFIER NOT NULL,
    [ZipCode]              VARCHAR (50)     NULL,
    [Image]                VARCHAR (100)    NULL,
    [CompanyId]            UNIQUEIDENTIFIER NOT NULL,
    [SchoolId]             UNIQUEIDENTIFIER NOT NULL,
    [LicenceNumber]        VARCHAR (50)     NULL,
    [LicenceIssueDate]     DATETIME         NULL,
    [LicenceValidUptoDate] DATETIME         NULL,
    [LicenceDescription]   VARCHAR (250)    NULL,
    [LicenceImage]         VARCHAR (100)    NULL,
    [LicenceType]          VARCHAR (50)     NULL,
    [IsActive]             BIT              DEFAULT ((1)) NOT NULL,
    [IsDeleted]            BIT              DEFAULT ((0)) NOT NULL,
    [CreatedBy]            UNIQUEIDENTIFIER NULL,
    [CreatedDate]          DATETIME         DEFAULT (getdate()) NOT NULL,
    [ModifiedBy]           UNIQUEIDENTIFIER NULL,
    [ModifiedDate]         DATETIME         NULL,
    [Status]               VARCHAR (10)     DEFAULT ('INC') NULL,
    [StatusMessage]        NVARCHAR (255)   NULL,
    CONSTRAINT [PK_DriverMaster] PRIMARY KEY CLUSTERED ([Id] ASC)
);

