CREATE TABLE [dbo].[EmpLeaveAvailDetails] (
    [Id]            UNIQUEIDENTIFIER NOT NULL,
    [EmployeeId]    UNIQUEIDENTIFIER NOT NULL,
    [LeaveTypeId]   UNIQUEIDENTIFIER NOT NULL,
    [ApplyDate]     DATETIME         NOT NULL,
    [StartDate]     DATETIME         NOT NULL,
    [EndDate]       DATETIME         NOT NULL,
    [TotalDays]     DECIMAL (18, 1)  NULL,
    [IsHalfDay]     BIT              NOT NULL,
    [Reason]        VARCHAR (250)    NULL,
    [Address]       VARCHAR (150)    NULL,
    [CityId]        UNIQUEIDENTIFIER NOT NULL,
    [StateId]       UNIQUEIDENTIFIER NOT NULL,
    [CountryId]     UNIQUEIDENTIFIER NOT NULL,
    [ZipCode]       VARCHAR (50)     NOT NULL,
    [ContactNumber] VARCHAR (50)     NULL,
    [SessionId]     UNIQUEIDENTIFIER NOT NULL,
    [IsActive]      BIT              NOT NULL,
    [IsDeleted]     BIT              NOT NULL,
    [CompanyId]     UNIQUEIDENTIFIER NOT NULL,
    [SchoolId]      UNIQUEIDENTIFIER NOT NULL,
    [CreatedBy]     UNIQUEIDENTIFIER NULL,
    [CreatedDate]   DATETIME         NOT NULL,
    [ModifiedBy]    UNIQUEIDENTIFIER NULL,
    [ModifiedDate]  DATETIME         NULL,
    [Status]        VARCHAR (10)     DEFAULT ('INC') NULL,
    [StatusMessage] NVARCHAR (255)   NULL,
    CONSTRAINT [PK_EmpLeaveAvailDetails] PRIMARY KEY CLUSTERED ([Id] ASC)
);

