CREATE TABLE [dbo].[EmpMaster] (
    [Id]                        UNIQUEIDENTIFIER NOT NULL,
    [Salutation]                VARCHAR (10)     NULL,
    [FirstName]                 VARCHAR (50)     NULL,
    [LastName]                  VARCHAR (50)     NULL,
    [DOB]                       DATETIME         NOT NULL,
    [FathersName]               VARCHAR (100)    NULL,
    [Gender]                    UNIQUEIDENTIFIER NOT NULL,
    [Description]               VARCHAR (100)    NULL,
    [DOJ]                       DATETIME         NOT NULL,
    [MaritalStatus]             VARCHAR (10)     NULL,
    [AadharNumber]              VARCHAR (50)     NULL,
    [BloodGroupId]              UNIQUEIDENTIFIER NOT NULL,
    [GradeId]                   UNIQUEIDENTIFIER NOT NULL,
    [Image]                     VARCHAR (150)    NULL,
    [OldEmployeeId]             UNIQUEIDENTIFIER NOT NULL,
    [YearsOfExperience]         VARCHAR (50)     NULL,
    [ProbationPeriod]           VARCHAR (50)     NULL,
    [ProbationStartDate]        DATETIME         NOT NULL,
    [ProbationEndDate]          DATETIME         NOT NULL,
    [ConfirmationDate]          DATETIME         NULL,
    [PANNumber]                 VARCHAR (50)     NULL,
    [ESICNumber]                VARCHAR (50)     NULL,
    [PFNumber]                  VARCHAR (50)     NULL,
    [CurrentAddress]            VARCHAR (150)    NULL,
    [CurrentAddressCityId]      UNIQUEIDENTIFIER NOT NULL,
    [CurrentAddressStateId]     UNIQUEIDENTIFIER NOT NULL,
    [CurrentAddressCountryId]   UNIQUEIDENTIFIER NOT NULL,
    [CurrentAddressZipCode]     VARCHAR (50)     NULL,
    [PermanentAddress]          VARCHAR (150)    NULL,
    [PermanentAddressCityId]    UNIQUEIDENTIFIER NOT NULL,
    [PermanentAddressStateId]   UNIQUEIDENTIFIER NOT NULL,
    [PermanentAddressCountryId] UNIQUEIDENTIFIER NOT NULL,
    [PermanentAddressZipCode]   VARCHAR (50)     NULL,
    [Phone]                     VARCHAR (50)     NULL,
    [Mobile]                    VARCHAR (50)     NULL,
    [Email]                     VARCHAR (100)    NULL,
    [DepartmentId]              UNIQUEIDENTIFIER NOT NULL,
    [DesignationId]             UNIQUEIDENTIFIER NOT NULL,
    [PaymentModeId]             UNIQUEIDENTIFIER NOT NULL,
    [TypeId]                    UNIQUEIDENTIFIER NOT NULL,
    [CategoryId]                UNIQUEIDENTIFIER NOT NULL,
    [BankAccountNumber]         VARCHAR (50)     NULL,
    [BankName]                  VARCHAR (100)    NULL,
    [BankAddress]               VARCHAR (150)    NULL,
    [BankAddressCityId]         UNIQUEIDENTIFIER NOT NULL,
    [BankAddressStateId]        UNIQUEIDENTIFIER NOT NULL,
    [BankAddressCountryId]      UNIQUEIDENTIFIER NOT NULL,
    [BankAddressZipCode]        VARCHAR (50)     NULL,
    [SchoolId]                  UNIQUEIDENTIFIER NOT NULL,
    [CompanyId]                 UNIQUEIDENTIFIER NOT NULL,
    [LicenceNumber]             VARCHAR (50)     NULL,
    [LicenceIssueDate]          DATETIME         NULL,
    [LicenceValidUptoDate]      DATETIME         NULL,
    [LicenceDescription]        VARCHAR (250)    NULL,
    [LicenceIssueState]         UNIQUEIDENTIFIER NOT NULL,
    [LicenceImage]              VARCHAR (100)    NULL,
    [LicenceType]               VARCHAR (50)     NULL,
    [DateOfLeaving]             DATETIME         NULL,
    [PreveiousSchoolCompany]    VARCHAR (150)    NULL,
    [MathsUpToClass]            BIT              NULL,
    [EnglishUpToClass]          BIT              NULL,
    [SSTUptoClass]              BIT              NULL,
    [IsActive]                  BIT              NOT NULL,
    [IsDeleted]                 BIT              NOT NULL,
    [CreatedBy]                 UNIQUEIDENTIFIER NULL,
    [CreatedDate]               DATETIME         NOT NULL,
    [ModifiedBy]                UNIQUEIDENTIFIER NULL,
    [ModifiedDate]              DATETIME         NULL,
    [Status]                    VARCHAR (10)     DEFAULT ('INC') NULL,
    [StatusMessage]             NVARCHAR (255)   NULL,
    CONSTRAINT [PK_EmpMaster] PRIMARY KEY CLUSTERED ([Id] ASC)
);

