CREATE TABLE [dbo].[ParentMaster] (
    [Id]              UNIQUEIDENTIFIER NOT NULL,
    [StudentGUID]     UNIQUEIDENTIFIER NOT NULL,
    [ParentFirstName] VARCHAR (50)     NOT NULL,
    [ParentLastName]  VARCHAR (50)     NOT NULL,
    [ParentDOB]       DATETIME         NULL,
    [QualifcationId]  INT              NULL,
    [Occupation]      VARCHAR (50)     NULL,
    [AnnualIncome]    DECIMAL (18, 2)  NULL,
    [Designation]     VARCHAR (50)     NULL,
    [Phone]           VARCHAR (50)     NULL,
    [Mobile]          VARCHAR (50)     NULL,
    [Email]           VARCHAR (50)     NULL,
    [Address]         VARCHAR (100)    NULL,
    [CityId]          UNIQUEIDENTIFIER NOT NULL,
    [StateId]         UNIQUEIDENTIFIER NOT NULL,
    [CountryId]       UNIQUEIDENTIFIER NOT NULL,
    [ZipCode]         VARCHAR (50)     NULL,
    [OfficeAddress]   VARCHAR (100)    NULL,
    [OfficeCityId]    UNIQUEIDENTIFIER NOT NULL,
    [OfficeStateId]   UNIQUEIDENTIFIER NOT NULL,
    [OfficeCountryId] UNIQUEIDENTIFIER NOT NULL,
    [OfficeZipCode]   VARCHAR (50)     NULL,
    [OfficePhone]     VARCHAR (50)     NULL,
    [Image]           VARCHAR (100)    NULL,
    [RelationTypeId]  UNIQUEIDENTIFIER NOT NULL,
    [SchoolId]        UNIQUEIDENTIFIER NOT NULL,
    [CompanyId]       UNIQUEIDENTIFIER NOT NULL,
    [IsActive]        BIT              DEFAULT ((1)) NOT NULL,
    [IsDeleted]       BIT              DEFAULT ((0)) NOT NULL,
    [CreatedBy]       UNIQUEIDENTIFIER NULL,
    [CreatedDate]     DATETIME         DEFAULT (getdate()) NOT NULL,
    [ModifiedBy]      UNIQUEIDENTIFIER NULL,
    [ModifiedDate]    DATETIME         NULL,
    [Status]          VARCHAR (10)     DEFAULT ('INC') NULL,
    [StatusMessage]   NVARCHAR (255)   NULL,
    CONSTRAINT [PK_ParentDetails] PRIMARY KEY CLUSTERED ([Id] ASC)
);

