CREATE TABLE [dbo].[RegistrationMaster] (
    [Id]                           UNIQUEIDENTIFIER NOT NULL,
    [RegistrationNumber]           VARCHAR (50)     NULL,
    [FirstName]                    VARCHAR (50)     NULL,
    [LastName]                     VARCHAR (50)     NULL,
    [DOB]                          DATETIME         NOT NULL,
    [Age]                          DECIMAL (18, 2)  NOT NULL,
    [ClassMasterId]                UNIQUEIDENTIFIER NOT NULL,
    [Date]                         DATETIME         NOT NULL,
    [SessionId]                    UNIQUEIDENTIFIER NOT NULL,
    [Address]                      VARCHAR (250)    NULL,
    [CityId]                       UNIQUEIDENTIFIER NOT NULL,
    [StateId]                      UNIQUEIDENTIFIER NOT NULL,
    [CountryId]                    UNIQUEIDENTIFIER NOT NULL,
    [ZipCode]                      VARCHAR (50)     NULL,
    [ContactNumber]                VARCHAR (50)     NULL,
    [Email]                        VARCHAR (100)    NULL,
    [Phone]                        VARCHAR (50)     NULL,
    [ReligionId]                   UNIQUEIDENTIFIER NOT NULL,
    [CategoryId]                   UNIQUEIDENTIFIER NOT NULL,
    [Gender]                       UNIQUEIDENTIFIER NOT NULL,
    [BloodGroupId]                 UNIQUEIDENTIFIER NOT NULL,
    [RegistrationFees]             DECIMAL (18, 2)  NULL,
    [RegistrationFeesPaid]         BIT              NULL,
    [SiblingsIfAny]                VARCHAR (50)     NULL,
    [SiblingClassMasterId]         UNIQUEIDENTIFIER NOT NULL,
    [FathersFirstName]             VARCHAR (50)     NULL,
    [FathersLastName]              VARCHAR (50)     NULL,
    [FathersDOB]                   DATETIME         NULL,
    [FathersQualificationId]       UNIQUEIDENTIFIER NOT NULL,
    [FathersOccupation]            VARCHAR (50)     NULL,
    [FathersDesignationId]         UNIQUEIDENTIFIER NOT NULL,
    [FathersAnnualIncome]          DECIMAL (18, 2)  NULL,
    [MothersFirstName]             VARCHAR (50)     NULL,
    [MothersLastName]              VARCHAR (50)     NULL,
    [MothersDOB]                   DATETIME         NULL,
    [MothersQualificationId]       UNIQUEIDENTIFIER NOT NULL,
    [MothersOccupation]            VARCHAR (50)     NULL,
    [MothersDesignationId]         UNIQUEIDENTIFIER NOT NULL,
    [MothersAnnualIncome]          DECIMAL (18, 2)  NULL,
    [BirthCertificate]             VARCHAR (100)    NULL,
    [BirthCertificateSubmitted]    BIT              NULL,
    [TransferCertificate]          VARCHAR (100)    NULL,
    [TransferCertificateSubmitted] BIT              NULL,
    [ReportCardLastClass]          VARCHAR (100)    NULL,
    [ReportCardSubmitted]          BIT              NULL,
    [OtherCertificateName]         VARCHAR (100)    NULL,
    [OtherCertificateSubmitted]    BIT              NULL,
    [OtherDescription]             VARCHAR (500)    NULL,
    [IsAdmissionConfirmed]         BIT              NULL,
    [StudentGuid]                  UNIQUEIDENTIFIER NULL,
    [CompanyId]                    UNIQUEIDENTIFIER NOT NULL,
    [SchoolId]                     UNIQUEIDENTIFIER NOT NULL,
    [IsActive]                     BIT              NOT NULL,
    [IsDeleted]                    BIT              NOT NULL,
    [CreatedBy]                    UNIQUEIDENTIFIER NULL,
    [CreatedDate]                  DATETIME         NOT NULL,
    [ModifiedBy]                   UNIQUEIDENTIFIER NULL,
    [ModifiedDate]                 DATETIME         NULL,
    [Status]                       VARCHAR (10)     DEFAULT ('INC') NULL,
    [StatusMessage]                NVARCHAR (255)   NULL,
    CONSTRAINT [PK_RegistrationMaster] PRIMARY KEY CLUSTERED ([Id] ASC)
);

