CREATE TABLE [dbo].[SchoolMaster] (
    [Id]                     UNIQUEIDENTIFIER NOT NULL,
    [Name]                   VARCHAR (50)     NULL,
    [Description]            VARCHAR (150)    NULL,
    [Email]                  VARCHAR (50)     NULL,
    [Address1]               VARCHAR (150)    NULL,
    [Address2]               VARCHAR (150)    NULL,
    [CityId]                 UNIQUEIDENTIFIER NULL,
    [StateId]                UNIQUEIDENTIFIER NULL,
    [CountryId]              UNIQUEIDENTIFIER NULL,
    [ZipCode]                VARCHAR (50)     NULL,
    [Phone]                  VARCHAR (50)     NULL,
    [EstablishmentYear]      CHAR (4)         NULL,
    [Mobile]                 VARCHAR (50)     NULL,
    [JudistrictionCityId]    UNIQUEIDENTIFIER NULL,
    [JudistrictionStateId]   UNIQUEIDENTIFIER NULL,
    [JudistrictionCountryId] UNIQUEIDENTIFIER NULL,
    [BankName]               VARCHAR (100)    NULL,
    [BankAddress1]           VARCHAR (250)    NULL,
    [BankAddress2]           VARCHAR (250)    NULL,
    [BankCityId]             UNIQUEIDENTIFIER NULL,
    [BankStateId]            UNIQUEIDENTIFIER NULL,
    [BankCountryId]          UNIQUEIDENTIFIER NULL,
    [BankZipCode]            VARCHAR (50)     NULL,
    [AccountNumber]          VARCHAR (100)    NULL,
    [IsActive]               BIT              DEFAULT ((1)) NOT NULL,
    [IsDeleted]              BIT              DEFAULT ((0)) NOT NULL,
    [CompanyId]              UNIQUEIDENTIFIER NOT NULL,
    [CreatedBy]              UNIQUEIDENTIFIER NULL,
    [CreatedDate]            DATETIME         DEFAULT (getdate()) NOT NULL,
    [ModifiedBy]             UNIQUEIDENTIFIER NULL,
    [ModifiedDate]           DATETIME         NULL,
    [Status]                 VARCHAR (10)     DEFAULT ('INC') NULL,
    [StatusMessage]          VARCHAR (250)    NULL,
    CONSTRAINT [PK_SchoolMaster] PRIMARY KEY CLUSTERED ([Id] ASC)
);

