CREATE TABLE [dbo].[SMSTask] (
    [Id]                     UNIQUEIDENTIFIER NOT NULL,
    [Name]                   VARCHAR (50)     NULL,
    [Description]            VARCHAR (150)    NULL,
    [NotificationSendEmail]  VARCHAR (1)      NOT NULL,
    [NotificationSendSMS]    VARCHAR (1)      NOT NULL,
    [NotificationReceiverId] UNIQUEIDENTIFIER NOT NULL,
    [RepeatSchedule]         VARCHAR (50)     NOT NULL,
    [Status_Id]              UNIQUEIDENTIFIER NOT NULL,
    [LastRunStatusId]        INT              NULL,
    [LastRunDate]            DATETIME         NULL,
    [IsReadOnly]             BIT              NULL,
    [CompanyId]              UNIQUEIDENTIFIER NOT NULL,
    [SchoolId]               UNIQUEIDENTIFIER NOT NULL,
    [IsActive]               BIT              DEFAULT ((1)) NOT NULL,
    [IsDeleted]              BIT              DEFAULT ((0)) NOT NULL,
    [CreatedBy]              UNIQUEIDENTIFIER NULL,
    [CreatedDate]            DATETIME         DEFAULT (getdate()) NOT NULL,
    [ModifiedBy]             UNIQUEIDENTIFIER NULL,
    [ModifiedDate]           DATETIME         NULL,
    [Status]                 VARCHAR (10)     DEFAULT ('INC') NULL,
    [StatusMessage]          NVARCHAR (255)   NULL,
    CONSTRAINT [PK_SMSTask] PRIMARY KEY CLUSTERED ([Id] ASC)
);

