CREATE TABLE [dbo].[StudentFeeDetailsHistory] (
    [Id]               UNIQUEIDENTIFIER NOT NULL,
    [StudentGUID]      UNIQUEIDENTIFIER NOT NULL,
    [ClassId]          UNIQUEIDENTIFIER NOT NULL,
    [SectionId]        UNIQUEIDENTIFIER NOT NULL,
    [DueDate]          DATETIME         NOT NULL,
    [PaidDate]         DATETIME         NULL,
    [IsPaid]           BIT              NOT NULL,
    [Amount]           DECIMAL (18, 2)  NULL,
    [LateFeeAmount]    DECIMAL (18, 2)  NULL,
    [TotalAmount]      DECIMAL (18, 2)  NULL,
    [FeeReceiptNumber] VARCHAR (50)     NULL,
    [Month]            UNIQUEIDENTIFIER NOT NULL,
    [Year]             UNIQUEIDENTIFIER NOT NULL,
    [SchoolId]         UNIQUEIDENTIFIER NOT NULL,
    [CompanyId]        UNIQUEIDENTIFIER NOT NULL,
    [IsActive]         BIT              DEFAULT ((1)) NOT NULL,
    [IsDeleted]        BIT              DEFAULT ((0)) NOT NULL,
    [CreatedBy]        UNIQUEIDENTIFIER NULL,
    [CreatedDate]      DATETIME         DEFAULT (getdate()) NOT NULL,
    [ModifiedBy]       UNIQUEIDENTIFIER NULL,
    [ModifiedDate]     DATETIME         NULL,
    [Status]           VARCHAR (10)     DEFAULT ('INC') NULL,
    [StatusMessage]    NVARCHAR (255)   NULL,
    CONSTRAINT [PK_StudentFeesDetailHistory] PRIMARY KEY CLUSTERED ([Id] ASC)
);

