CREATE TABLE [dbo].[StudentMarksDetails] (
    [Id]               UNIQUEIDENTIFIER NOT NULL,
    [StudentGUID]      UNIQUEIDENTIFIER NOT NULL,
    [SujectCategoryId] UNIQUEIDENTIFIER NOT NULL,
    [SessionId]        UNIQUEIDENTIFIER NOT NULL,
    [Marks1Q1]         DECIMAL (18, 2)  NULL,
    [Marks2Q1]         DECIMAL (18, 2)  NULL,
    [Marks1Q2]         DECIMAL (18, 2)  NULL,
    [Marks2Q2]         DECIMAL (18, 2)  NULL,
    [Marks1Q3]         DECIMAL (18, 2)  NULL,
    [Marks2Q3]         DECIMAL (18, 2)  NULL,
    [MarksFA1]         DECIMAL (18, 2)  NULL,
    [MarksFA2]         DECIMAL (18, 2)  NULL,
    [MarksFA3]         DECIMAL (18, 2)  NULL,
    [MarksFA4]         DECIMAL (18, 2)  NULL,
    [MarksSA1]         DECIMAL (18, 2)  NULL,
    [MarksSA2]         DECIMAL (18, 2)  NULL,
    [ClassId]          UNIQUEIDENTIFIER NOT NULL,
    [SectionId]        UNIQUEIDENTIFIER NOT NULL,
    [CompanyId]        UNIQUEIDENTIFIER NOT NULL,
    [SchoolId]         UNIQUEIDENTIFIER NOT NULL,
    [IsActive]         BIT              DEFAULT ((1)) NOT NULL,
    [IsDeleted]        BIT              DEFAULT ((0)) NOT NULL,
    [CreatedBy]        UNIQUEIDENTIFIER NULL,
    [CreatedDate]      DATETIME         DEFAULT (getdate()) NOT NULL,
    [ModifiedBy]       UNIQUEIDENTIFIER NULL,
    [ModifiedDate]     DATETIME         NULL,
    [Status]           VARCHAR (10)     DEFAULT ('INC') NULL,
    [StatusMessage]    NVARCHAR (255)   NULL,
    CONSTRAINT [PK_StudentMarksDetails] PRIMARY KEY CLUSTERED ([Id] ASC)
);

