CREATE TABLE [dbo].[StudentGradeDetails] (
    [Id]            UNIQUEIDENTIFIER NOT NULL,
    [StudentGUID]   UNIQUEIDENTIFIER NOT NULL,
    [SessionId]     UNIQUEIDENTIFIER NOT NULL,
    [CategoryId]    UNIQUEIDENTIFIER NOT NULL,
    [GradeQ1]       VARCHAR (10)     NULL,
    [GradeQ2]       VARCHAR (10)     NULL,
    [GradeQ3]       VARCHAR (10)     NULL,
    [GradeFA1]      VARCHAR (10)     NULL,
    [GradeFA2]      VARCHAR (10)     NULL,
    [GradeFA3]      VARCHAR (10)     NULL,
    [GradeFA4]      VARCHAR (10)     NULL,
    [GradeSA1]      VARCHAR (10)     NULL,
    [GradeSA2]      VARCHAR (10)     NULL,
    [ClassId]       UNIQUEIDENTIFIER NOT NULL,
    [SectionId]     UNIQUEIDENTIFIER NOT NULL,
    [CompanyId]     UNIQUEIDENTIFIER NOT NULL,
    [SchoolId]      UNIQUEIDENTIFIER NOT NULL,
    [IsActive]      BIT              DEFAULT ((1)) NOT NULL,
    [IsDeleted]     BIT              DEFAULT ((0)) NOT NULL,
    [CreatedBy]     UNIQUEIDENTIFIER NULL,
    [CreatedDate]   DATETIME         DEFAULT (getdate()) NOT NULL,
    [ModifiedBy]    UNIQUEIDENTIFIER NULL,
    [ModifiedDate]  DATETIME         NULL,
    [Status]        VARCHAR (10)     DEFAULT ('INC') NULL,
    [StatusMessage] NVARCHAR (255)   NULL,
    CONSTRAINT [PK_StudentGradeDetails] PRIMARY KEY CLUSTERED ([Id] ASC)
);

