CREATE TABLE [dbo].[StudentReportCardDetailsHistory] (
    [Id]                UNIQUEIDENTIFIER NOT NULL,
    [ReportCardId]      UNIQUEIDENTIFIER NOT NULL,
    [SubjectType]       VARCHAR (50)     NULL,
    [SubjectId]         INT              NULL,
    [QuarterMarks]      DECIMAL (18, 2)  NULL,
    [MarksFA1]          DECIMAL (18, 2)  NULL,
    [MarksFA2]          DECIMAL (18, 2)  NULL,
    [MarksSA]           DECIMAL (18, 2)  NULL,
    [Grade]             VARCHAR (10)     NULL,
    [GradeFA1]          VARCHAR (10)     NULL,
    [GradeFA2]          VARCHAR (10)     NULL,
    [GradeSA]           VARCHAR (10)     NULL,
    [TotalMarks]        DECIMAL (18, 2)  NULL,
    [TotalGrade]        VARCHAR (10)     NULL,
    [TotalMarksQuarter] DECIMAL (18, 2)  NULL,
    [TotalMMarksFA1]    DECIMAL (18, 2)  NULL,
    [TotalMMarksFA2]    DECIMAL (18, 2)  NULL,
    [TotalMMarksSA]     DECIMAL (18, 2)  NULL,
    [TotalMMarksFinal]  DECIMAL (18, 2)  NULL,
    [CompanyId]         UNIQUEIDENTIFIER NOT NULL,
    [SchoolId]          UNIQUEIDENTIFIER NOT NULL,
    [IsActive]          BIT              DEFAULT ((1)) NOT NULL,
    [IsDeleted]         BIT              DEFAULT ((0)) NOT NULL,
    [CreatedBy]         UNIQUEIDENTIFIER NULL,
    [CreatedDate]       DATETIME         DEFAULT (getdate()) NOT NULL,
    [ModifiedBy]        UNIQUEIDENTIFIER NULL,
    [ModifiedDate]      DATETIME         NULL,
    [Status]            VARCHAR (10)     DEFAULT ('INC') NULL,
    [StatusMessage]     NVARCHAR (255)   NULL,
    CONSTRAINT [PK_StudentReportCardDetailsHistory] PRIMARY KEY CLUSTERED ([Id] ASC)
);

