CREATE TABLE [dbo].[StudentMaster] (
    [StudentGUID]                  UNIQUEIDENTIFIER NOT NULL,
    [RollNumber]                   UNIQUEIDENTIFIER NOT NULL,
    [FirstName]                    VARCHAR (100)    NULL,
    [LastName]                     VARCHAR (100)    NULL,
    [Address]                      VARCHAR (150)    NULL,
    [CityId]                       UNIQUEIDENTIFIER NOT NULL,
    [StateId]                      UNIQUEIDENTIFIER NOT NULL,
    [CountryId]                    UNIQUEIDENTIFIER NOT NULL,
    [ZipCode]                      VARCHAR (50)     NULL,
    [ContactNumber]                VARCHAR (50)     NULL,
    [EmergencyContactNumber]       VARCHAR (50)     NULL,
    [DOB]                          DATETIME         NOT NULL,
    [DOJ]                          DATETIME         NOT NULL,
    [RegistrationNumber]           VARCHAR (50)     NOT NULL,
    [ClassId]                      UNIQUEIDENTIFIER NOT NULL,
    [SectionId]                    UNIQUEIDENTIFIER NOT NULL,
    [HouseAllotted]                VARCHAR (50)     NULL,
    [Transport]                    VARCHAR (50)     NULL,
    [Image]                        VARCHAR (150)    NULL,
    [Email]                        VARCHAR (50)     NULL,
    [CategoryId]                   UNIQUEIDENTIFIER NOT NULL,
    [SiblingsIfAny]                VARCHAR (50)     NULL,
    [SiblingClassId]               INT              NULL,
    [Gender]                       VARCHAR (10)     NULL,
    [DisabilityAny]                VARCHAR (50)     NULL,
    [MedicalAlleryAny]             VARCHAR (50)     NULL,
    [BirthPlace]                   VARCHAR (50)     NULL,
    [BithCityId]                   UNIQUEIDENTIFIER NOT NULL,
    [BirthStateId]                 UNIQUEIDENTIFIER NOT NULL,
    [BithCountryId]                UNIQUEIDENTIFIER NOT NULL,
    [PreviousSchoolAttended]       VARCHAR (100)    NULL,
    [PreviousSchoolClassId]        UNIQUEIDENTIFIER NOT NULL,
    [PreviousSchoolPercentage]     DECIMAL (18, 2)  NULL,
    [PreviousSchoolRank]           VARCHAR (50)     NULL,
    [PreviousSchoolBoardId]        UNIQUEIDENTIFIER NOT NULL,
    [PreviousSchoolFronDate]       DATETIME         NULL,
    [PreviousSchoolToDate]         DATETIME         NULL,
    [WithdrawnDate]                DATETIME         NULL,
    [WithdrawnReason]              VARCHAR (150)    NULL,
    [BloodGroupId]                 UNIQUEIDENTIFIER NOT NULL,
    [Nationality]                  UNIQUEIDENTIFIER NOT NULL,
    [Hobbies]                      VARCHAR (150)    NULL,
    [ReligionId]                   UNIQUEIDENTIFIER NOT NULL,
    [Phone]                        VARCHAR (50)     NULL,
    [RouteId]                      UNIQUEIDENTIFIER NOT NULL,
    [RouteStopDetailsId]           UNIQUEIDENTIFIER NOT NULL,
    [ClassTeacherId]               UNIQUEIDENTIFIER NOT NULL,
    [RoutePickAndDrop]             UNIQUEIDENTIFIER NOT NULL,
    [FeesDiscountCategoryMasterId] UNIQUEIDENTIFIER NOT NULL,
    [TutionFees]                   DECIMAL (18, 2)  NULL,
    [AnnialFees]                   DECIMAL (18, 2)  NULL,
    [TransportFees]                DECIMAL (18, 2)  NULL,
    [UseTransportFees]             BIT              NULL,
    [SessionId]                    UNIQUEIDENTIFIER NOT NULL,
    [CompanyId]                    UNIQUEIDENTIFIER NOT NULL,
    [SchoolId]                     UNIQUEIDENTIFIER NOT NULL,
    [IsActive]                     BIT              DEFAULT ((1)) NOT NULL,
    [IsDeleted]                    BIT              DEFAULT ((0)) NOT NULL,
    [CreatedBy]                    UNIQUEIDENTIFIER NULL,
    [CreatedDate]                  DATETIME         DEFAULT (getdate()) NOT NULL,
    [ModifiedBy]                   UNIQUEIDENTIFIER NULL,
    [ModifiedDate]                 DATETIME         NULL,
    [Status]                       VARCHAR (10)     DEFAULT ('INC') NULL,
    [StatusMessage]                NVARCHAR (255)   NULL,
    CONSTRAINT [PK_StudentMaster] PRIMARY KEY CLUSTERED ([StudentGUID] ASC)
);

