CREATE TABLE [dbo].[TeacherMaster] (
    [Id]                UNIQUEIDENTIFIER NOT NULL,
    [FirstName]         VARCHAR (50)     NOT NULL,
    [LastName]          VARCHAR (50)     NULL,
    [DOB]               DATETIME         NOT NULL,
    [DOJ]               DATETIME         NULL,
    [Date_OF_LEAVING]   DATETIME         NULL,
    [Address]           VARCHAR (100)    NULL,
    [CityId]            UNIQUEIDENTIFIER NULL,
    [StateId]           UNIQUEIDENTIFIER NULL,
    [ZipCode]           VARCHAR (50)     NULL,
    [GENDER]            VARCHAR (10)     NOT NULL,
    [MaritalStatus]     VARCHAR (10)     NULL,
    [Image]             VARCHAR (100)    NULL,
    [Phone]             VARCHAR (50)     NULL,
    [MobilePhone]       VARCHAR (50)     NULL,
    [YearsOfExperience] VARCHAR (50)     NULL,
    [PreviousSchool]    VARCHAR (150)    NULL,
    [Salutation]        VARCHAR (10)     NULL,
    [Email]             VARCHAR (150)    NULL,
    [CompanyId]         UNIQUEIDENTIFIER NOT NULL,
    [SchoolId]          UNIQUEIDENTIFIER NOT NULL,
    [IsActive]          BIT              DEFAULT ((1)) NOT NULL,
    [IsDeleted]         BIT              DEFAULT ((0)) NOT NULL,
    [CreatedBy]         UNIQUEIDENTIFIER NULL,
    [CreatedDate]       DATETIME         DEFAULT (getdate()) NOT NULL,
    [ModifiedBy]        UNIQUEIDENTIFIER NULL,
    [ModifiedDate]      DATETIME         NULL,
    [Status]            VARCHAR (10)     DEFAULT ('INC') NULL,
    [StatusMessage]     NVARCHAR (255)   NULL,
    CONSTRAINT [PK_TeacherMaster] PRIMARY KEY CLUSTERED ([Id] ASC)
);

