CREATE TABLE [dbo].[TimeTableSetupDetailsHistory] (
    [Id]                     UNIQUEIDENTIFIER NOT NULL,
    [SessionId]              UNIQUEIDENTIFIER NOT NULL,
    [SchoolStartTime]        TIME (0)         NOT NULL,
    [SchoolEndTime]          TIME (0)         NOT NULL,
    [PeriodStartTime]        TIME (0)         NOT NULL,
    [TotalPeriods]           INT              NOT NULL,
    [PeriodDuration]         INT              NOT NULL,
    [RecessDuration]         INT              NOT NULL,
    [RecessAfterPeriod]      INT              NOT NULL,
    [FruitRecessDuration]    INT              NULL,
    [FruitRecessAfterPeriod] INT              NULL,
    [CompanyId]              UNIQUEIDENTIFIER NOT NULL,
    [SchoolId]               UNIQUEIDENTIFIER NOT NULL,
    [IsActive]               BIT              DEFAULT ((1)) NOT NULL,
    [IsDeleted]              BIT              DEFAULT ((0)) NOT NULL,
    [CreatedBy]              UNIQUEIDENTIFIER NULL,
    [CreatedDate]            DATETIME         DEFAULT (getdate()) NOT NULL,
    [ModifiedBy]             UNIQUEIDENTIFIER NULL,
    [ModifiedDate]           DATETIME         NULL,
    [Status]                 VARCHAR (10)     DEFAULT ('INC') NULL,
    [StatusMessage]          NVARCHAR (255)   NULL,
    CONSTRAINT [PK_TimeTableSetupDetailsHistory] PRIMARY KEY CLUSTERED ([Id] ASC)
);

