CREATE TABLE [dbo].[VendorMaster] (
    [Id]            UNIQUEIDENTIFIER NOT NULL,
    [VendorName]    VARCHAR (50)     NULL,
    [Description]   VARCHAR (150)    NULL,
    [Address]       VARCHAR (100)    NULL,
    [CityId]        UNIQUEIDENTIFIER NOT NULL,
    [StateId]       UNIQUEIDENTIFIER NOT NULL,
    [CountryId]     UNIQUEIDENTIFIER NOT NULL,
    [ZipCode]       VARCHAR (150)    NULL,
    [ContactNumber] VARCHAR (50)     NULL,
    [Mobile_Phone]  VARCHAR (50)     NULL,
    [Email]         VARCHAR (50)     NULL,
    [CompanyId]     UNIQUEIDENTIFIER NOT NULL,
    [SchoolId]      UNIQUEIDENTIFIER NOT NULL,
    [IsActive]      BIT              DEFAULT ((1)) NOT NULL,
    [IsDeleted]     BIT              DEFAULT ((0)) NOT NULL,
    [CreatedBy]     UNIQUEIDENTIFIER NULL,
    [CreatedDate]   DATETIME         DEFAULT (getdate()) NOT NULL,
    [ModifiedBy]    UNIQUEIDENTIFIER NULL,
    [ModifiedDate]  DATETIME         NULL,
    [Status]        VARCHAR (10)     DEFAULT ('INC') NULL,
    [StatusMessage] NVARCHAR (255)   NULL,
    CONSTRAINT [PK_VendorMaster] PRIMARY KEY CLUSTERED ([Id] ASC)
);

